[pytest]
addopts =
    -ra
    --cov=.
    --cov-config=.coveragerc
    --cov-report=term-missing:skip-covered
    --cov-report=xml:output/metadata/coverage.xml
    --cov-report=html:output/metadata/coverage_html
